### ISSUE TITLE
Attendance Report 

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/attendance#4]
The below format should be used for attendance report of multiple users.

![](https://cloud.githubusercontent.com/assets/527591/5627797/7619c25e-95bf-11e4-8055-503c0a7133e4.png)

**Comment by MuhammadAmmad** [comment]
its done plz chk 
http://smsserver.esajee.com/atte/Service1.svc/getHorizontalReport?user_id=attendance::user::6::4&sdate=2015-01-01&edate=2015-01-31
